# Generated by Django 5.0.6 on 2024-06-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrofuture', '0002_rename_categoty_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellng_price',
            new_name='selling_price',
        ),
    ]
